version: '3.8'

networks:
  lms_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms_network

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lms_network

  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - lms_network
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Amsterdam
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    depends_on:
      - api-edtech
      - janus
      - minio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/data # Stores acme.json for SSL certs
    command:
      - --global.checkNewVersion=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Automatic HTTP to HTTPS redirect
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # Certificate Resolver for Name.com
      - --certificatesresolvers.myresolver.acme.email=${NAMECOM_USERNAME}
      - --certificatesresolvers.myresolver.acme.storage=/data/acme.json
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=namecom

  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    container_name: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lms_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-api.rule=Host(`minio.edtech.works`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls.certresolver=myresolver"
      - "traefik.http.routers.minio-api.service=minio-api-svc"
      - "traefik.http.services.minio-api-svc.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.rule=Host(`minio-console.edtech.works`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
      - "traefik.http.routers.minio-console.service=minio-console-svc"
      - "traefik.http.services.minio-console-svc.loadbalancer.server.port=9001"

  janus:
    image: canyan/janus-gateway:latest
    container_name: janus
    restart: unless-stopped
    ports:
      - "10000-10200:10000-10200/udp"
    volumes:
      - ./janus-recordings:/tmp/janus-recordings
    command: [ "/usr/local/bin/janus", "-S", "stun.l.google.com:19302" ]
    networks:
      - lms_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.janus.rule=Host(`janus.edtech.works`)"
      - "traefik.http.routers.janus.entrypoints=websecure"
      - "traefik.http.routers.janus.tls.certresolver=myresolver"
      - "traefik.http.services.janus.loadbalancer.server.port=8088"

  api-edtech:
    build:
      context: ./api-edtech
    container_name: api-edtech
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
    networks:
      - lms_network
    depends_on:
      - db
      - rabbitmq
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-edtech.rule=Host(`api.edtech.works`)"
      - "traefik.http.routers.api-edtech.entrypoints=websecure"
      - "traefik.http.routers.api-edtech.tls.certresolver=myresolver"
      - "traefik.http.services.api-edtech.loadbalancer.server.port=${API_PORT}"

  agentic-rag:
    build:
      context: ./agentic-rag
      dockerfile: Dockerfile
    container_name: agentic-rag-api
    depends_on:
      - db
      - rabbitmq
      - minio
    volumes:
      - chroma-data:/app/.chroma
      - ./agentic-rag/knowledge-base:/app/knowledge-base:ro
    restart: always
    env_file:
      - .env
    networks:
      - lms_network

  transcode-video-worker:
    build:
      context: ./transcode-video-worker
    container_name: transcode-video-worker
    depends_on:
      - db
      - rabbitmq
      - minio
    volumes:
      - ./.env:/app/.env
    networks:
      - lms_network
    restart: always

volumes:
  db_data:
  minio_data:
  chroma-data:
  traefik_data: