version: '3.8'

networks:
  lms_network:
    driver: bridge

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - lms_network
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Amsterdam
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - traefik:/certs

  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lms_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-api.rule=Host(`minio.edtech.works`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls.certresolver=myresolver"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.rule=Host(`minio.dashboard.edtech.works`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

  janus:
    image: canyan/janus-gateway:latest
    container_name: janus
    restart: unless-stopped
    ports:
      - "10000-10200:10000-10200/udp"
      - "8000:8000"
    volumes:
      - ${HOST_PROJECT_PATH}/janus-recordings:/tmp/janus-recordings
    command: [ "/usr/local/bin/janus", "-S", "stun.l.google.com:19302" ]
    networks:
      - lms_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.janus.rule=Host(`janus.edtech.works`)"
      - "traefik.http.routers.janus.entrypoints=websecure"
      - "traefik.http.routers.janus.tls.certresolver=myresolver"
      - "traefik.http.services.janus.loadbalancer.server.port=8088"

  api-edtech:
    build:
      context: ./api-edtech
    container_name: api-edtech
    restart: always
    env_file:
      - .env
    networks:
      - lms_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-edtech.rule=Host(`api.edtech.works`)"
      - "traefik.http.routers.api-edtech.entrypoints=websecure"
      - "traefik.http.routers.api-edtech.tls.certresolver=myresolver"
      - "traefik.http.services.api-edtech.loadbalancer.server.port=${API_PORT}"

  agentic-rag:
    build:
      context: ./agentic-rag
      dockerfile: Dockerfile
    container_name: agentic-rag-api
    ports:
      - "8001:8001"
    volumes:
      - chroma-data:/app/.chroma
      - ${HOST_PROJECT_PATH}/agentic-rag/knowledge-base:/app/knowledge-base:ro
    restart: always
    env_file:
      - .env
    networks:
      - lms_network

  transcode-video-worker:
    build:
      context: ./transcode-video-worker
    container_name: transcode-video-worker
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - lms_network
    restart: always

volumes:
  db_data:
  minio_data:
  chroma-data:
  traefik:
